spring.application.name=library

spring.datasource.url = 
spring.datasource.username = 
spring.datasource.password = 
spring.datasource.driver-class-name= 

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=
jwt.expiration= 